name: nwchem_singularity

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '59 15 * * FRI'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-dev.ompi40x
#            - nwchem-701.mpich321.ivybridge
    steps:
    - name: Checkout nwchem-singularity source
      uses: actions/checkout@v2
    - name: Setup cache
      id: setup-cache
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
        key: ${{ matrix.folder}}-nwchemcache-v005
    - name: fetch cache
      if: steps.setup-cache.outputs.cache-hit == 'true'
      run: |
        if [[ -f ~/cache/ompi/lib/libmpi.so ]]; then \
        echo "ompi cache present" ; \
        fi
        if [[ -f ~/cache/libext/lib/libnwc_openblas.a ]]; then \
        echo "libext cache present" ; \
        fi
        if [[ -f ~/cache/simint.l*.install/lib/libnwc_simint.a ]]; then \
        echo "simint cache present" ; \
        fi
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: Checkout nwchem source
      uses: actions/checkout@v2
      with:
        repository: nwchemgit/nwchem
        clean: false
        path: nwchem
        fetch-depth: 1
    - name: build a singularity container
      run: |
        cd ${{ matrix.folder }}
        singularity build --fakeroot ${{ matrix.folder }}.simg  Singularity
    - name: store cache
      run: |
        mkdir -p ~/cache || true
        cd ${{ matrix.folder }}
        singularity exec ${{ matrix.folder }}.simg cp -r /opt/ompi ~/cache
        singularity exec ${{ matrix.folder }}.simg cp -rv /nwchem/src/libext ~/cache/. ||true
        singularity exec ${{ matrix.folder }}.simg ls -la /nwchem/src/NWints/simint/libsimint_source/simint.l5_p5_d1.install || true
        singularity exec ${{ matrix.folder }}.simg ls -la /nwchem/src/NWints/simint/libsimint_source/ || true
        singularity exec ${{ matrix.folder }}.simg ls -la /nwchem/src/NWints/simint || true
        singularity exec ${{ matrix.folder }}.simg ls -la /nwchem/src/NWints/ || true
        singularity exec ${{ matrix.folder }}.simg cp -rv /nwchem/src/NWints/simint/libsimint_source/simint.l5_p5_d1.install ~/cache/. ||true
        echo "cache stored"
        ls -l ~/cache
        ls -R ~/cache
    - name: find image file
      run: |
        cd ${{ matrix.folder }}
        find . -name ${{ matrix.folder }}.simg
        cd ..
        find . -name ${{ matrix.folder }}.simg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.folder }}
        path: ${{ matrix.folder }}/${{ matrix.folder }}.simg
    - name: push to ghcr.io
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io
        singularity remote list
        singularity push ${{ matrix.folder }}/${{ matrix.folder }}.simg oras://ghcr.io/${{ github.repository }}/${{ matrix.folder }}:latest
    - name: testimage
      run: |
        export OMPI_VERSION=4.0.7
        pwd
        ls -la
        wget https://download.open-mpi.org/release/open-mpi/v4.0/openmpi-$OMPI_VERSION.tar.bz2
        tar xjf openmpi-$OMPI_VERSION.tar.bz2
        cd openmpi-$OMPI_VERSION
        ./configure --prefix=$GITHUB_WORKSPACE/ompi407 --enable-mpi1-compatibility
        make -j3
        make -j3 install
        cd ..
        rm -f */*simg
        singularity pull ${{ matrix.folder }}/${{ matrix.folder }}.simg oras://ghcr.io/${{ github.repository }}/${{ matrix.folder }}:latest
        cd nwchem/QA
        export UCX_TLS=tcp,self
        export UCX_POSIX_USE_PROC_LINK=n
        export PATH=$GITHUB_WORKSPACE/ompi407/bin:$PATH
        export MPIRUN_NPOPT="-x UCX_POSIX_USE_PROC_LINK=n -x UCX_TLS=tcp,self -n"
        export LD_LIBRARY_PATH=$GITHUB_WORKSPACE/ompi407/bin:$LD_LIBRARY_PATH
        which mpirun
        export NWCHEM_EXECUTABLE="singularity exec oras://ghcr.io/edoapra/nwchem-singularity/nwchem-dev.ompi40x:latest nwchem"
        ./runtests.mpi.unix procs 2 dft_he2+
        ./runtests.mpi.unix procs 2 h2o_opt
