name: nwchem_singularity

on:
  push:
  pull_request:
  release:
  schedule:
    - cron: '59 15 * * FRI'
  repository_dispatch:
    types: [backend_automation]
  workflow_dispatch:

jobs:
  build_image:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          folder:
            - nwchem-701.mpich321.ivybridge
    steps:
    - uses: actions/checkout@v2
    - uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.3
    - name: build a singularity container
      run: |
        cd ${{ matrix.folder }}
        singularity build --fakeroot ${{ matrix.folder }}.simg  Singularity
    - name: find image file
      run: |
        cd ${{ matrix.folder }}
        find . -name ${{ matrix.folder }}.simg
        cd ..
        find . -name ${{ matrix.folder }}.simg
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.folder }}/${{ matrix.folder }}.simg
        path: nwchem_${{ matrix.folder }}.simg
